<?php

namespace Database\Seeders;

use App\Models\AssessmentQuestion;
use Illuminate\Database\Seeder;

class AssessmentQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            ['technology' => 'Frontend', 'topic' => 'HTML', 'difficulty' => 'Beginner', 'question' => 'Which HTML element is best for the main navigation section of a page?', 'options' => ['<section>', '<nav>', '<header>', '<main>'], 'correct_answer' => '<nav>', 'explanation' => 'The <nav> element is intended for a group of major navigation links.'],
            ['technology' => 'Frontend', 'topic' => 'CSS', 'difficulty' => 'Beginner', 'question' => 'What does `display: flex` primarily help with?', 'options' => ['Server-side rendering', 'Layout alignment and distribution', 'Data fetching', 'Form validation'], 'correct_answer' => 'Layout alignment and distribution', 'explanation' => 'Flexbox is used to align, space, and order items in a layout.'],
            ['technology' => 'Frontend', 'topic' => 'JavaScript', 'difficulty' => 'Beginner', 'question' => 'Which array method creates a new array by transforming every item?', 'options' => ['forEach', 'filter', 'map', 'find'], 'correct_answer' => 'map', 'explanation' => '`map` returns a new array containing transformed values.'],
            ['technology' => 'Frontend', 'topic' => 'React', 'difficulty' => 'Intermediate', 'question' => 'Why is a `key` prop important when rendering lists in React?', 'options' => ['It encrypts props', 'It helps React identify changed items', 'It adds styling hooks', 'It memoizes the list'], 'correct_answer' => 'It helps React identify changed items', 'explanation' => 'Keys help React reconcile list item updates efficiently.'],
            ['technology' => 'Frontend', 'topic' => 'Accessibility', 'difficulty' => 'Intermediate', 'question' => 'What is the main purpose of an `aria-label`?', 'options' => ['To change font size', 'To improve SEO only', 'To provide an accessible name for assistive tech', 'To lazy-load components'], 'correct_answer' => 'To provide an accessible name for assistive tech', 'explanation' => '`aria-label` gives screen readers an accessible label when visible text is missing.'],
            ['technology' => 'Frontend', 'topic' => 'State Management', 'difficulty' => 'Intermediate', 'question' => 'When should local component state usually be lifted upward?', 'options' => ['When multiple components need the same data', 'When CSS becomes difficult', 'When routes change', 'When forms are short'], 'correct_answer' => 'When multiple components need the same data', 'explanation' => 'Shared state should typically live in the nearest common parent.'],
            ['technology' => 'Frontend', 'topic' => 'Performance', 'difficulty' => 'Intermediate', 'question' => 'Which practice most directly improves perceived loading speed on a UI screen?', 'options' => ['Using longer variable names', 'Showing skeleton states', 'Adding more nested divs', 'Inlining all scripts'], 'correct_answer' => 'Showing skeleton states', 'explanation' => 'Skeleton states make the interface feel responsive while content loads.'],

            ['technology' => 'Backend', 'topic' => 'PHP', 'difficulty' => 'Beginner', 'question' => 'What does a PHP associative array store?', 'options' => ['Only numbers', 'Key-value pairs', 'Only strings', 'Only functions'], 'correct_answer' => 'Key-value pairs', 'explanation' => 'Associative arrays use named keys mapped to values.'],
            ['technology' => 'Backend', 'topic' => 'Laravel', 'difficulty' => 'Beginner', 'question' => 'Which Laravel feature maps URLs to controller actions?', 'options' => ['Queues', 'Routes', 'Events', 'Policies'], 'correct_answer' => 'Routes', 'explanation' => 'Routes define how incoming requests are handled.'],
            ['technology' => 'Backend', 'topic' => 'Databases', 'difficulty' => 'Beginner', 'question' => 'What is the primary role of a database index?', 'options' => ['Encrypt tables', 'Speed up lookups', 'Resize columns', 'Remove duplicates automatically'], 'correct_answer' => 'Speed up lookups', 'explanation' => 'Indexes improve query performance for frequent search patterns.'],
            ['technology' => 'Backend', 'topic' => 'APIs', 'difficulty' => 'Intermediate', 'question' => 'Which HTTP method is most appropriate for updating an existing resource completely?', 'options' => ['GET', 'POST', 'PUT', 'OPTIONS'], 'correct_answer' => 'PUT', 'explanation' => 'PUT is commonly used to replace or fully update an existing resource.'],
            ['technology' => 'Backend', 'topic' => 'Authentication', 'difficulty' => 'Intermediate', 'question' => 'Why should passwords be hashed before storage?', 'options' => ['To sort users faster', 'To prevent plain text exposure', 'To compress user data', 'To improve session speed'], 'correct_answer' => 'To prevent plain text exposure', 'explanation' => 'Hashed passwords reduce risk if the database is exposed.'],
            ['technology' => 'Backend', 'topic' => 'Eloquent', 'difficulty' => 'Intermediate', 'question' => 'What problem does eager loading solve in Laravel?', 'options' => ['N+1 query issues', 'CSS conflicts', 'Routing loops', 'Token expiration'], 'correct_answer' => 'N+1 query issues', 'explanation' => 'Eager loading fetches related models efficiently to avoid repeated queries.'],
            ['technology' => 'Backend', 'topic' => 'Validation', 'difficulty' => 'Beginner', 'question' => 'What should server-side validation protect against?', 'options' => ['Only browser refreshes', 'Invalid or malicious input', 'Slow CSS animations', 'Duplicate comments in code'], 'correct_answer' => 'Invalid or malicious input', 'explanation' => 'Validation ensures input meets rules and protects application integrity.'],

            ['technology' => 'Full Stack', 'topic' => 'Architecture', 'difficulty' => 'Intermediate', 'question' => 'What is a common benefit of separating frontend and backend concerns?', 'options' => ['Fewer variables', 'Better maintainability and scaling', 'No need for APIs', 'Automatic testing'], 'correct_answer' => 'Better maintainability and scaling', 'explanation' => 'Separation of concerns makes teams and systems easier to scale and maintain.'],
            ['technology' => 'Full Stack', 'topic' => 'APIs', 'difficulty' => 'Intermediate', 'question' => 'What does JSON most often represent in web applications?', 'options' => ['Database schema files', 'Structured data payloads', 'Stylesheets', 'Compiled assets'], 'correct_answer' => 'Structured data payloads', 'explanation' => 'JSON is a standard format for structured data exchange between systems.'],
            ['technology' => 'Full Stack', 'topic' => 'Security', 'difficulty' => 'Intermediate', 'question' => 'What does CSRF protection help prevent?', 'options' => ['Unauthorized forged requests', 'Slow SQL queries', 'Layout shifts', 'Broken SVG icons'], 'correct_answer' => 'Unauthorized forged requests', 'explanation' => 'CSRF tokens help confirm requests actually originated from the user session.'],
            ['technology' => 'Full Stack', 'topic' => 'Deployment', 'difficulty' => 'Beginner', 'question' => 'Why is environment configuration usually stored outside source code?', 'options' => ['To avoid using routes', 'To keep secrets and environment differences manageable', 'To disable caching', 'To remove dependencies'], 'correct_answer' => 'To keep secrets and environment differences manageable', 'explanation' => 'Environment files keep secrets and deploy-specific values out of code.'],
            ['technology' => 'Full Stack', 'topic' => 'Debugging', 'difficulty' => 'Intermediate', 'question' => 'What is the most helpful first step when debugging a failing request flow?', 'options' => ['Rename all files', 'Reproduce the problem consistently', 'Change the database', 'Delete caches immediately'], 'correct_answer' => 'Reproduce the problem consistently', 'explanation' => 'A stable reproduction path makes diagnosis much faster and more reliable.'],
            ['technology' => 'Full Stack', 'topic' => 'Projects', 'difficulty' => 'Intermediate', 'question' => 'Which project habit helps most when features get larger?', 'options' => ['Skipping naming conventions', 'Breaking work into clear modules', 'Keeping all logic in one file', 'Avoiding code review'], 'correct_answer' => 'Breaking work into clear modules', 'explanation' => 'Modular structure reduces complexity and improves maintainability.'],

            ['technology' => 'AI/ML', 'topic' => 'Python', 'difficulty' => 'Beginner', 'question' => 'Why is Python popular in AI and data workflows?', 'options' => ['It has no syntax rules', 'It has strong libraries and readable syntax', 'It only runs in browsers', 'It replaces databases'], 'correct_answer' => 'It has strong libraries and readable syntax', 'explanation' => 'Python combines accessibility with a rich ecosystem for data and ML work.'],
            ['technology' => 'AI/ML', 'topic' => 'Data', 'difficulty' => 'Beginner', 'question' => 'What is the purpose of cleaning a dataset before training?', 'options' => ['To add more random values', 'To improve data quality and consistency', 'To remove all labels', 'To avoid writing code'], 'correct_answer' => 'To improve data quality and consistency', 'explanation' => 'Cleaner data usually leads to more reliable training and evaluation.'],
            ['technology' => 'AI/ML', 'topic' => 'Model Evaluation', 'difficulty' => 'Intermediate', 'question' => 'What is a validation set mainly used for?', 'options' => ['Final production backups', 'Choosing and tuning models during development', 'Replacing the training set', 'Designing UI components'], 'correct_answer' => 'Choosing and tuning models during development', 'explanation' => 'Validation data helps compare and tune models before final testing.'],
            ['technology' => 'AI/ML', 'topic' => 'Machine Learning', 'difficulty' => 'Intermediate', 'question' => 'What is overfitting?', 'options' => ['A model learning noise too closely', 'A database lock', 'A CSS overflow issue', 'A larger batch size'], 'correct_answer' => 'A model learning noise too closely', 'explanation' => 'Overfitting happens when a model memorizes patterns that do not generalize well.'],
            ['technology' => 'AI/ML', 'topic' => 'Features', 'difficulty' => 'Intermediate', 'question' => 'What is feature engineering?', 'options' => ['Drawing charts', 'Preparing or transforming inputs to help a model learn', 'Deploying servers', 'Reducing CSS bundle size'], 'correct_answer' => 'Preparing or transforming inputs to help a model learn', 'explanation' => 'Good features can significantly improve model performance.'],
            ['technology' => 'AI/ML', 'topic' => 'LLM Basics', 'difficulty' => 'Intermediate', 'question' => 'What is a prompt in an LLM workflow?', 'options' => ['A database index', 'The input instruction or context sent to the model', 'A GPU temperature warning', 'A deployment certificate'], 'correct_answer' => 'The input instruction or context sent to the model', 'explanation' => 'Prompts shape how the model responds to a task.'],

            ['technology' => 'DSA', 'topic' => 'Arrays', 'difficulty' => 'Beginner', 'question' => 'Which data structure stores items in contiguous order and allows index access?', 'options' => ['Tree', 'Graph', 'Array', 'Stack trace'], 'correct_answer' => 'Array', 'explanation' => 'Arrays provide direct access using numeric indexes.'],
            ['technology' => 'DSA', 'topic' => 'Complexity', 'difficulty' => 'Beginner', 'question' => 'What does Big O notation describe?', 'options' => ['Color contrast', 'Algorithm growth relative to input size', 'Database passwords', 'Framework versions'], 'correct_answer' => 'Algorithm growth relative to input size', 'explanation' => 'Big O expresses how time or space grows as input size increases.'],
            ['technology' => 'DSA', 'topic' => 'Strings', 'difficulty' => 'Beginner', 'question' => 'What is a palindrome?', 'options' => ['A sorted number list', 'A string that reads the same both ways', 'A recursive tree', 'An encrypted file'], 'correct_answer' => 'A string that reads the same both ways', 'explanation' => 'A palindrome has mirrored order from left to right and right to left.'],
            ['technology' => 'DSA', 'topic' => 'Recursion', 'difficulty' => 'Intermediate', 'question' => 'Why does a recursive function need a base case?', 'options' => ['To increase file size', 'To stop infinite self-calls', 'To create loops faster', 'To skip memory usage'], 'correct_answer' => 'To stop infinite self-calls', 'explanation' => 'The base case ends recursion and prevents endless calls.'],
            ['technology' => 'DSA', 'topic' => 'Searching', 'difficulty' => 'Intermediate', 'question' => 'When is binary search applicable?', 'options' => ['Only on unsorted lists', 'On sorted collections', 'Only on linked lists', 'Only in databases'], 'correct_answer' => 'On sorted collections', 'explanation' => 'Binary search relies on order to halve the search space.'],
            ['technology' => 'DSA', 'topic' => 'Problem Solving', 'difficulty' => 'Intermediate', 'question' => 'What usually helps most before writing code for an algorithm question?', 'options' => ['Guessing the final answer', 'Working through a small example by hand', 'Skipping constraints', 'Memorizing syntax'], 'correct_answer' => 'Working through a small example by hand', 'explanation' => 'Small examples reveal patterns and edge cases clearly.'],

            ['technology' => 'Mobile', 'topic' => 'Flutter', 'difficulty' => 'Beginner', 'question' => 'What are Flutter UIs primarily built from?', 'options' => ['Widgets', 'Routes only', 'SQL models', 'Blade templates'], 'correct_answer' => 'Widgets', 'explanation' => 'Flutter composes interfaces from reusable widgets.'],
            ['technology' => 'Mobile', 'topic' => 'State', 'difficulty' => 'Intermediate', 'question' => 'Why is state management important in mobile apps?', 'options' => ['It controls app icons only', 'It keeps UI and data changes predictable', 'It replaces navigation', 'It removes API usage'], 'correct_answer' => 'It keeps UI and data changes predictable', 'explanation' => 'State management coordinates how data changes update the UI.'],
            ['technology' => 'Mobile', 'topic' => 'Performance', 'difficulty' => 'Intermediate', 'question' => 'What can reduce unnecessary rebuilds in a mobile UI?', 'options' => ['Updating every widget each frame', 'Scoping state changes carefully', 'Using larger images', 'Putting all logic in build methods'], 'correct_answer' => 'Scoping state changes carefully', 'explanation' => 'Targeted state updates reduce extra rendering work.'],
            ['technology' => 'Mobile', 'topic' => 'UX', 'difficulty' => 'Beginner', 'question' => 'Which design choice most improves form usability on phones?', 'options' => ['Tiny tap targets', 'Clear labels and spacing', 'More modal popups', 'Auto-playing videos'], 'correct_answer' => 'Clear labels and spacing', 'explanation' => 'Readable labels and generous spacing make forms easier to use on touch devices.'],
            ['technology' => 'Mobile', 'topic' => 'APIs', 'difficulty' => 'Intermediate', 'question' => 'Why should mobile apps handle loading and error states explicitly?', 'options' => ['To make screens look empty', 'Because network calls are unreliable and asynchronous', 'To remove caching', 'Because stores require it'], 'correct_answer' => 'Because network calls are unreliable and asynchronous', 'explanation' => 'Mobile apps need clear states for delayed or failed network requests.'],
            ['technology' => 'Mobile', 'topic' => 'Testing', 'difficulty' => 'Intermediate', 'question' => 'What is the benefit of widget or UI tests in mobile development?', 'options' => ['They replace all manual testing', 'They verify user flows and UI behavior', 'They create assets automatically', 'They increase app size'], 'correct_answer' => 'They verify user flows and UI behavior', 'explanation' => 'UI-level tests catch regressions in visible behavior and interaction flow.'],

            ['technology' => 'Data Science', 'topic' => 'Pandas', 'difficulty' => 'Beginner', 'question' => 'What is a common reason to use a DataFrame in data work?', 'options' => ['To draw SVG icons', 'To organize and analyze tabular data', 'To host APIs', 'To compile CSS'], 'correct_answer' => 'To organize and analyze tabular data', 'explanation' => 'DataFrames are a standard structure for working with tabular datasets.'],
            ['technology' => 'Data Science', 'topic' => 'Cleaning', 'difficulty' => 'Beginner', 'question' => 'Why should missing values be handled before analysis?', 'options' => ['To slow down notebooks', 'To reduce misleading results', 'To disable plotting', 'To increase storage'], 'correct_answer' => 'To reduce misleading results', 'explanation' => 'Missing data can distort summaries, models, and visualizations if ignored.'],
            ['technology' => 'Data Science', 'topic' => 'Visualization', 'difficulty' => 'Intermediate', 'question' => 'What makes a chart useful for decision making?', 'options' => ['Dense decoration', 'Clear encoding of the important comparison', 'Random colors', 'Long legends only'], 'correct_answer' => 'Clear encoding of the important comparison', 'explanation' => 'Good charts make the key comparison easy to read and interpret.'],
            ['technology' => 'Data Science', 'topic' => 'Statistics', 'difficulty' => 'Intermediate', 'question' => 'What does an average help summarize?', 'options' => ['The center of a numeric distribution', 'The file size of the dataset', 'The number of charts', 'The query plan'], 'correct_answer' => 'The center of a numeric distribution', 'explanation' => 'A mean is one way to summarize central tendency in numeric data.'],
            ['technology' => 'Data Science', 'topic' => 'Reasoning', 'difficulty' => 'Intermediate', 'question' => 'Why should analysts question outliers before presenting insights?', 'options' => ['They might indicate errors or special cases', 'They always prove the conclusion', 'They remove the need for context', 'They are required in every chart'], 'correct_answer' => 'They might indicate errors or special cases', 'explanation' => 'Outliers can be meaningful, but they can also reflect data issues or unusual cases.'],

            ['technology' => 'DevOps', 'topic' => 'CLI', 'difficulty' => 'Beginner', 'question' => 'Why is command-line familiarity valuable in DevOps work?', 'options' => ['It replaces source control', 'It enables automation and repeatable operations', 'It removes cloud usage', 'It draws architecture diagrams'], 'correct_answer' => 'It enables automation and repeatable operations', 'explanation' => 'The command line is central to scripting, automation, and server operations.'],
            ['technology' => 'DevOps', 'topic' => 'Containers', 'difficulty' => 'Beginner', 'question' => 'What problem do containers commonly help solve?', 'options' => ['Inconsistent runtime environments', 'Weak typography', 'Missing route names', 'Slow mouse input'], 'correct_answer' => 'Inconsistent runtime environments', 'explanation' => 'Containers package dependencies so apps behave more consistently across environments.'],
            ['technology' => 'DevOps', 'topic' => 'CI/CD', 'difficulty' => 'Intermediate', 'question' => 'What is a core benefit of CI pipelines?', 'options' => ['They avoid all bugs', 'They run checks automatically on code changes', 'They replace databases', 'They eliminate monitoring'], 'correct_answer' => 'They run checks automatically on code changes', 'explanation' => 'CI pipelines provide fast feedback on tests, builds, and quality checks.'],
            ['technology' => 'DevOps', 'topic' => 'Deployment', 'difficulty' => 'Intermediate', 'question' => 'Why is rollback capability important in deployment workflows?', 'options' => ['It makes logs shorter', 'It helps recover quickly from bad releases', 'It removes version control', 'It disables alerts'], 'correct_answer' => 'It helps recover quickly from bad releases', 'explanation' => 'Rollbacks reduce downtime and risk when a release introduces problems.'],
            ['technology' => 'DevOps', 'topic' => 'Monitoring', 'difficulty' => 'Intermediate', 'question' => 'What does monitoring primarily support after deployment?', 'options' => ['Understanding system health and failures', 'Choosing font families', 'Writing HTML faster', 'Compressing assets'], 'correct_answer' => 'Understanding system health and failures', 'explanation' => 'Monitoring helps teams detect incidents and understand service behavior over time.'],

            ['technology' => 'Projects', 'topic' => 'Scope', 'difficulty' => 'Beginner', 'question' => 'What makes a project easier to finish well?', 'options' => ['Unlimited feature scope', 'A clear and constrained goal', 'No deadlines', 'Skipping planning'], 'correct_answer' => 'A clear and constrained goal', 'explanation' => 'Tighter scope makes quality and delivery more realistic.'],
            ['technology' => 'Projects', 'topic' => 'Portfolio', 'difficulty' => 'Beginner', 'question' => 'Why do project writeups help a portfolio?', 'options' => ['They hide the project code', 'They explain decisions and impact', 'They replace the UI', 'They remove the need for testing'], 'correct_answer' => 'They explain decisions and impact', 'explanation' => 'Strong writeups show how you think, not just what you built.'],
            ['technology' => 'Projects', 'topic' => 'Iteration', 'difficulty' => 'Intermediate', 'question' => 'What is a strong way to improve a project after the first version ships?', 'options' => ['Ignore feedback', 'Review usage gaps and refine based on them', 'Delete the README', 'Add random features'], 'correct_answer' => 'Review usage gaps and refine based on them', 'explanation' => 'Iteration works best when it is driven by actual gaps or feedback.'],
            ['technology' => 'Projects', 'topic' => 'Quality', 'difficulty' => 'Intermediate', 'question' => 'Which trait makes a project feel more professional?', 'options' => ['Broken empty states', 'Polished edge cases and consistency', 'Unused pages', 'Very long loading times'], 'correct_answer' => 'Polished edge cases and consistency', 'explanation' => 'Professional products usually feel intentional in both common and edge cases.'],
            ['technology' => 'Projects', 'topic' => 'Delivery', 'difficulty' => 'Intermediate', 'question' => 'Why is deployment part of project readiness?', 'options' => ['It proves the work can be accessed and demonstrated', 'It removes all bugs', 'It replaces documentation', 'It avoids APIs'], 'correct_answer' => 'It proves the work can be accessed and demonstrated', 'explanation' => 'Deployment turns a code project into a usable artifact others can review.'],
        ];

        foreach ($questions as $question) {
            AssessmentQuestion::updateOrCreate(
                [
                    'technology' => $question['technology'],
                    'topic' => $question['topic'],
                    'question' => $question['question'],
                ],
                $question
            );
        }
    }
}
